[build]
  publish = "dist"
  functions = "src/netlify/functions"
  command = "vite build"

[dev]
  publish = "dist"
  functions = "src/netlify/functions"
  framework = "vite"
  targetPort = 5173
  port = 8888
  
[functions]
  node_bundler = "esbuild"
  ignore_text = "*.test.ts"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200