[build]
  publish = "dist"
  functions = "public/netlify/functions"
  command = "vite build"

[dev]
  publish = "dist"
  functions = "public/netlify/functions"
  framework = "vite"
  targetPort = 5173
  port = 8888
  
[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"